# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171011_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=255, null=True, verbose_name='Название ресторана')),
            ],
            options={
                'verbose_name_plural': 'Названия ресторанов',
                'verbose_name': 'Название ресторана',
            },
        ),
        migrations.CreateModel(
            name='Waiters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiter_name', models.CharField(max_length=255, null=True, verbose_name='Имя официанта')),
            ],
            options={
                'verbose_name_plural': 'Имена официантов',
                'verbose_name': 'Имя официанта',
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.AddField(
            model_name='order',
            name='order_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OrderPlace'),
        ),
        migrations.AddField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Waiters'),
        ),
    ]
