# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_waiters_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiters',
            old_name='place',
            new_name='work_place',
        ),
    ]
