# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171011_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='item_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_place',
            field=models.ForeignKey(default='Moscow', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.OrderPlace'),
        ),
    ]
