# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171011_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.IntegerField(null=True),
        ),
    ]
